### ISSUE TITLE
JARS Training for new ops staff

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/documentation#51]
## Background

The team needs some cross training on JARS so it can train new ops staff

**Comment by ClaireTroughtonJAC** [comment]
Umesh to pick up

**Comment by UmeshxSolanki** [comment]
Spoke to Jackie.  She is willing to be trained to give the training to the new staff. Jackie has capacity to do this training.  
She estimates there are b/w 20 to 27 new staff who need this. 
Jackie to let me know if Kas disagrees, otherwise assume Kas is onboard. 
Umesh needs to 
- [ ] Review existing material ... which Claire uses. 
- [ ] Review what Farhana has created in terms of a manual.  
- [ ] Outline approach to Sharon
- [ ] Agree with Jackie who is to create any other material.

**Comment by UmeshxSolanki** [comment]
- [ ] Work out how to get the last remaining 6 people on the course.

**Comment by UmeshxSolanki** [comment]
- [ ] Send HoOps progress update email

**Comment by UmeshxSolanki** [comment]
Stopped learning Session 2, to write HoOps QT Board paper.  Request came through on email.
