### ISSUE TITLE
Staff Suggestion:  Category (i) and Schedule 2(d)

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/documentation#93]
Review profile
Review application form template
Work with Kas 

Claire to get Kas/Linda to provide query

**Comment by UmeshxSolanki** [comment]
Notes from Staff Suggestion:

If you are applying for a legal post, or if you are a lawyer, you must complete the legal experience section. When filling in the 'law-related activity' section, you should only choose category i) if you do not have experience in any of the other categories listed.

If you don’t understand what I mean, look at any large exercise e.g. 104 DDJ(MC). Out of 874 applicants, 231 have eligibility flagged. Granted, many of those will be because they have minor Character issues, but a significant proportion will have un-necessarily selected Category (i) within their Legal Experience part of their application. Perhaps the same warning could become part of the Information page template too?

Also – why do Character issues flag as Eligibility? Is this to ensure staff check all for major ones so they can be raised at Eligibility SCC? Is the saving made on not interviewing a non-eligible candidate more than the large amounts of staff time required to check every application during Eligibility checks that has been flagged, only to find they have minor Character issues?
